apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  namespace: gcp-devops-dev
  labels:
    app: gcp-devops-app-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-devops-app-dev
  template:
    metadata:
      labels:
        app: gcp-devops-app-dev
    spec:
      containers:
        - name: gcp-devops-app-dev
          image: gcr.io/project-7989/gcp-devops-app-dev
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
---
apiVersion: v1
kind: Service
metadata:
  name: gcp-devops-gke-service
  namespace: gcp-devops-dev
  labels:
    app.kubernetes.io/managed-by: gcp-cloud-build-deploy
spec:
  selector:
    app: gcp-devops-app-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: LoadBalancer
