apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
  labels:
    app: gcp-devops-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-devops-app
  template:
    metadata:
      labels:
        app: gcp-devops-app
    spec:
      containers:
        - name: gcp-devops-app
          image: gcr.io/project-7989/gcp-devops-app  # No :tag here; Cloud Build replaces it
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              value: "5000"
