apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-devops-gke
spec:
replicas: 1
selector:
  matchLabels:
    app: gcp-devops-gke
  template:
    metadata:
      labels:    
        app: gcp-devops-gke
    containers:
    - name: gcp-devops-gke
      image: gcr.io/project-7989/gcp-devops-app:latest
      ports:     
      - containerPort: 5000
      env:
        - name: PORT    
          value: "5000"